quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

quotes/quoteapp/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=30, null=False, unique=True)
    biography = models.TextField()

    def __str__(self):
        return f'{self.fullname}'


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, Textarea
from django.db import models
from .models import Author, Quote


class AuthorForm(ModelForm):

    fullname = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    biography = Textarea()

    class Meta:
        model = Author
        fields = ['fullname', 'biography']


class QuoteForm(ModelForm):

    quote = Textarea()

    # choices = []
    #
    # for i, author in enumerate(Author.objects.all()):
    #     choices.append((author, author))

    author = ModelChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Quote
        fields = ['quote', 'author']

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/quoteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AuthorForm, QuoteForm
from .models import Author, Quote

# Create your views here.

def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quoteapp/index.html', {'quotes': quotes})

def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})

def quote(request):
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)

        # author_id = Author.objects.get(id=request.POST.get('authors'))
        # print(author_id)
        # form.author = author_id

        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            # print(form)
            # print(form.errors)

            return render(request, 'quoteapp/quote.html', {'authors': authors, 'form': form})

    return render(request, 'quoteapp/quote.html', {'form': QuoteForm()})

def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quoteapp/detail.html', {'quote': quote})

quotes/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm

# Create your views here.

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quoteapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'users/signup.html', context={'form': form})

    return render(request, 'users/signup.html', context={'form': RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quoteapp:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quoteapp:main')

    return render(request, 'users/login.html', context={'form': LoginForm()})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = 'An email with instructions to reset your password has been sent to %(email)s'
    subject_template_name = 'users/password_reset_subject.txt'


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quoteapp:main')

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author full name:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author biography:
            {{ form.biography }}
        </label>
        <span>{{ form.errors.biography }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quote information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %} {% block content %}

<h1>{{quote.author.fullname}}</h1>
<p>Biography: <b>{{quote.author.biography}}</b></p>

{% endblock %}

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quoteapp:quote' %}" role="button">Add quote</a></li>
            <li><a href="{% url 'quoteapp:author' %}" role="button">Add author</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
        <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
        <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    {% for quote in quotes %}
    <ul>
        <li>
            <a href="{% url 'quoteapp:detail' quote.id %}" role="button" class="outline"> {{ quote.quote }} </a>
        </li>
    </ul>
    {% endfor %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            {{ form.author }}
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/users/templates/users/login.html
{% extends "quoteapp/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/password_reset.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset complete!</h2>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }}</p>
<p>You requested a password reset for your account. Please follow this link to set a new password.</p>
<p>
  <a href="{{ protocol }}:/{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
    {{ protocol }}:/{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
  </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
</body>
{% endautoescape %}

quotes/users/templates/users/signup.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span> {{ form.errors.email }} </span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}